
name: wap01s_venv
channels:
  - conda-forge
  - defaults
  - mro
dependencies:
  - matplotlib=3.0.*
  - pandas=0.24.*
  - python=3.7.*
  - scikit-learn=0.20.*
  - seaborn=0.9.*
  - Pillow==8.3.2
  - pip=19.0.*
  - pip:
      - streamlit==1.1.0
      
